name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current version number
        id: info
        run:
          DESIRED_VERSION="$(gh release list --repo=https://github.com/cloudflare/cloudflared | grep Latest | awk '{ print $1 }')"
          echo "desired-version=${DESIRED_VERSION}" >> "${GITHUB_OUTPUT}"
          echo "today=$(date '+%Y-%m-%d')" >> "${GITHUB_OUTPUT}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            "COMMENT=Today's date: ${{ steps.info.today }}"
            "DESIRED_VERSION=${{ steps.info.desired-version }}"
          tags: |
           bennettp123/cloudflared:${{ steps.info.desired-version }}
           bennettp123/cloudflared:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
